name: Release
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
        default: '0.0.1'
      snapshotVersion:
        description: 'Snapshot Version'
        required: true
        default: '0.1.0-SNAPSHOT'
      branch:
        description: 'Branch to Release'
        required: false
        default: 'main'
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Update Sources
        run: |
          .github/scripts/setVersions.sh "${{ github.event.inputs.releaseVersion }}" "v${{ github.event.inputs.releaseVersion }}" "v${{ github.event.inputs.releaseVersion }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Test Build Image
        uses: docker/build-push-action@v6
        with:
          context: data-generator/
          platforms: linux/amd64,linux/arm64
          push: false
          file: data-generator/Dockerfile
      - name: Push Tag
        run: |
          git push
          git push origin "v${{ github.event.inputs.releaseVersion }}"
      - name: Image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.IMAGE_REPO_HOSTNAME }}/${{ secrets.IMAGE_REPO_NAMESPACE }}/flink-examples-data-generator
          tags: |
            type=raw,value=v${{ github.event.inputs.releaseVersion }}
            type=raw,value=latest
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: "${{ secrets.IMAGE_REPO_HOSTNAME }}"
          username: "${{ secrets.IMAGE_REPO_USERNAME }}"
          password: "${{ secrets.IMAGE_REPO_PASSWORD }}"
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: data-generator/
          platforms: linux/amd64,linux/arm64
          push: true
          file: data-generator/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update Sources for Development
        run: |
          .github/scripts/setVersions.sh "${{ github.event.inputs.snapshotVersion }}" "latest"
          git push
